networks:
  ask-zoie-net:
    driver: bridge

services:
  bot-service:
    build:
      context: ./bot-service
      dockerfile: Dockerfile
    container_name: askzoie-bot-service
    env_file:
      - ./bot-service/.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ask-zoie-net
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: askzoie-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: chatbotdb
      POSTGRES_USER: zoie
      POSTGRES_PASSWORD: zoie
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ask-zoie-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zoie -d chatbotdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: askzoie-server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ask-zoie-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: askzoie-client
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - ask-zoie-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pgdata: