networks:
  ask-zoie-net:
    driver: bridge

services:
  postgres:
    image: postgres:15-alpine
    container_name: askzoie-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: chatbotdb
      POSTGRES_USER: zoie
      POSTGRES_PASSWORD: zoie
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ask-zoie-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zoie -d chatbotdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: askzoie-server
    environment:
      DATABASE_URL: postgres://zoie:zoie@postgres:5432/chatbotdb
      PORT: 3000
      FRONTEND_URL: "http://localhost:80/"
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ask-zoie-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: askzoie-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - ask-zoie-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pgdata: